name: Build Backend

on:
  push:
    paths:
      - "server/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./server
        run: |
          npm install
          # npm run build  # Descomenta si usas TypeScript u otro build step
