name: Deploy Backend

on:
  push:
    paths:
      - "server/**"
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./server
        run: |
          npm install
          # npm run build  # Descomenta si usas TypeScript

      - name: Deploy to Azure Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_BACKEND }}
          package: ./server
